name: Deploy Python mutator script to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'climatemutator123456'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7BCA6717F6514D4398E888D77F3B9FDD }}
          package: .
          
      - name: Set Azure Web App startup command
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az webapp config set \
              --name climatemutator123456 \
              --resource-group <RESOURCE_GROUP_NAME> \
              --startup-file "/home/site/wwwroot/venv/bin/python /home/site/wwwroot/mutator.py https://azclimate123456-etdyc8fjgkanfddb.swedencentral-01.azurewebsites.net/api/reg 99"
